### ISSUE TITLE
exercise 1, review result

### ISSUE THREAD

**Issue by wojski** [rosaba/test-repository#2]
`<button onclick="myFunction()">nextsite</button> ` // Not a menu item ;)

hardcoded page name(blee)

```
alert("good choice, here comes page2");
        window.open("page2.html");
```

`if (r == true) {`  Unnecessary variable, better:    `  if (confirm("Do you want to be redirected?")) {`

Maybe better to think about make function like this?
It's make code more generic, and that allow you to simply use this method for all links on page :)

```
<button onclick="myFunction('page2')">nextsite</button>
  <script>
    function myFunction(pageName) {
      if (confirm("Do you want to be redirected?")) {
        alert("good choice, here comes "+pageName);
        window.open(pageName+".html");
          }
      else {
        alert("lazy something, you are missing the chance to visit"+pageName);
          }
        }
    </script>
```

**Comment by rosaba** [comment]
what do you mean by "hardcoded page name(blee)"?

**Comment by rosaba** [comment]
well, this is my new solution. but still struggling with github (tutorial is not reality ;) ) so i am sharing this here first::

<!doctype html>
<html>
<head>
  <title>exercise 1</title>
  <link rel="stylesheet" type="text/css" href="main.css">
</head>

<body>
  <header>
    <nav>
      <h1>exerciseONE</h1>
      <ul>
        <li><button onclick="redirectToSite(pageName[0])">Home</button></li>
        <li><button onclick="redirectToSite(pageName[1])">About</button></li>
        <li><button onclick="redirectToSite(pageName[2])">How</button></li>
        <li><button onclick="redirectToSite(pageName[3])">FAQ</button></li>
      </ul>
    </nav>
  </header>
  <div class="row">
    <div class="col"></div>
    <div class="col"></div>
    <div class="col"></div>
  </div>


  <script>
    var pageName = ["index", "about", "how", "faq"];
    function redirectToSite(pageName) {
      if (confirm("Do you want to be redirected?")) {
        alert("good choice, here comes " + pageName);
        window.open(pageName + ".html");
          }
      else {
        alert("lazy something, you are missing the chance to visit " + pageName);
          }
        }
    </script>

<footer>

</footer>
</body>

</html>

**Comment by rosaba** [comment]
well, this is my solution. still struggling with github (tutorial != reality ;)) so i am sharing this here for the moment till I get it real on git::

`<!doctype html>
<html>
<head>
  <title>exercise 1</title>
  <link rel="stylesheet" type="text/css" href="main.css">
</head>

<body>
  <header>
    <nav>
      <h1>exerciseONE</h1>
      <ul>
        <li><button onclick="redirectToSite(pageName[0])">Home</button></li>
        <li><button onclick="redirectToSite(pageName[1])">About</button></li>
        <li><button onclick="redirectToSite(pageName[2])">How</button></li>
        <li><button onclick="redirectToSite(pageName[3])">FAQ</button></li>
      </ul>
    </nav>
  </header>
  <div class="row">
    <div class="col"></div>
    <div class="col"></div>
    <div class="col"></div>
  </div>


  <script>
    var pageName = ["index", "about", "how", "faq"];
    function redirectToSite(pageName) {
      if (confirm("Do you want to be redirected?")) {
        alert("good choice, here comes " + pageName);
        window.open(pageName + ".html");
          }
      else {
        alert("lazy something, you are missing the chance to visit " + pageName);
          }
        }
    </script>

<footer>

</footer>
</body>

</html>
`

**Comment by rosaba** [comment]
`<!doctype html>
<html>
<head>
  <title>exercise 1</title>
  <link rel="stylesheet" type="text/css" href="main.css">
</head>

<body>
  <header>
    <nav>
      <h1>exerciseONE</h1>
      <ul>
        <li><button onclick="redirectToSite(pageName[0])">Home</button></li>
        <li><button onclick="redirectToSite(pageName[1])">About</button></li>
        <li><button onclick="redirectToSite(pageName[2])">How</button></li>
        <li><button onclick="redirectToSite(pageName[3])">FAQ</button></li>
      </ul>
    </nav>
  </header>
  <div class="row">
    <div class="col"></div>
    <div class="col"></div>
    <div class="col"></div>
  </div>


  <script>
    var pageName = ["index", "about", "how", "faq"];
    function redirectToSite(pageName) {
      if (confirm("Do you want to be redirected?")) {
        alert("good choice, here comes " + pageName);
        window.open(pageName + ".html");
          }
      else {
        alert("lazy something, you are missing the chance to visit " + pageName);
          }
        }
    </script>

<footer>

</footer>
</body>

</html>`

**Comment by rosaba** [comment]
> 
<!doctype html>
<html>
<head>
  <title>exercise 1</title>
  <link rel="stylesheet" type="text/css" href="main.css">
</head>

<body>
  <header>
    <nav>
      <h1>exerciseONE</h1>
      <ul>
        <li><button onclick="redirectToSite(pageName[0])">Home</button></li>
        <li><button onclick="redirectToSite(pageName[1])">About</button></li>
        <li><button onclick="redirectToSite(pageName[2])">How</button></li>
        <li><button onclick="redirectToSite(pageName[3])">FAQ</button></li>
      </ul>
    </nav>
  </header>
  <div class="row">
    <div class="col"></div>
    <div class="col"></div>
    <div class="col"></div>
  </div>


  <script>
    var pageName = ["index", "about", "how", "faq"];
    function redirectToSite(pageName) {
      if (confirm("Do you want to be redirected?")) {
        alert("good choice, here comes " + pageName);
        window.open(pageName + ".html");
          }
      else {
        alert("lazy something, you are missing the chance to visit " + pageName);
          }
        }
    </script>

<footer>

</footer>
</body>

</html>

**Comment by rosaba** [comment]
`<!doctype html>
<html>
<head>
  <title>exercise 1</title>
  <link rel="stylesheet" type="text/css" href="main.css">
</head>

<body>
  <header>
    <nav>
      <h1>exerciseONE</h1>
      <ul>
        <li><button onclick="redirectToSite(pageName[0])">Home</button></li>
        <li><button onclick="redirectToSite(pageName[1])">About</button></li>
        <li><button onclick="redirectToSite(pageName[2])">How</button></li>
        <li><button onclick="redirectToSite(pageName[3])">FAQ</button></li>
      </ul>
    </nav>
  </header>
  <div class="row">
    <div class="col"></div>
    <div class="col"></div>
    <div class="col"></div>
  </div>


  <script>
    var pageName = ["index", "about", "how", "faq"];
    function redirectToSite(pageName) {
      if (confirm("Do you want to be redirected?")) {
        alert("good choice, here comes " + pageName);
        window.open(pageName + ".html");
          }
      else {
        alert("lazy something, you are missing the chance to visit " + pageName);
          }
        }
    </script>

<footer>

</footer>
</body>

</html>`

**Comment by rosaba** [comment]
<!doctype html>
<html>
<head>
  <title>exercise 1</title>
  <link rel="stylesheet" type="text/css" href="main.css">
</head>

<body>
  <header>
    <nav>
      <h1>exerciseONE</h1>
      <ul>
        <li><button onclick="redirectToSite(pageName[0])">Home</button></li>
        <li><button onclick="redirectToSite(pageName[1])">About</button></li>
        <li><button onclick="redirectToSite(pageName[2])">How</button></li>
        <li><button onclick="redirectToSite(pageName[3])">FAQ</button></li>
      </ul>
    </nav>
  </header>
  <div class="row">
    <div class="col"></div>
    <div class="col"></div>
    <div class="col"></div>
  </div>


  <script>
    var pageName = ["index", "about", "how", "faq"];
    function redirectToSite(pageName) {
      if (confirm("Do you want to be redirected?")) {
        alert("good choice, here comes " + pageName);
        window.open(pageName + ".html");
          }
      else {
        alert("lazy something, you are missing the chance to visit " + pageName);
          }
        }
    </script>

<footer>

</footer>
</body>

</html>

**Comment by rosaba** [comment]
`<head>
  <title>exercise 1</title>
  <link rel="stylesheet" type="text/css" href="main.css">
</head>

<body>
  <header>
    <nav>
      <h1>exerciseONE</h1>
      <ul>
        <li><button onclick="redirectToSite(pageName[0])">Home</button></li>
        <li><button onclick="redirectToSite(pageName[1])">About</button></li>
        <li><button onclick="redirectToSite(pageName[2])">How</button></li>
        <li><button onclick="redirectToSite(pageName[3])">FAQ</button></li>
      </ul>
    </nav>
  </header>
  <div class="row">
    <div class="col"></div>
    <div class="col"></div>
    <div class="col"></div>
  </div>


  <script>
    var pageName = ["index", "about", "how", "faq"];
    function redirectToSite(pageName) {
      if (confirm("Do you want to be redirected?")) {
        alert("good choice, here comes " + pageName);
        window.open(pageName + ".html");
          }
      else {
        alert("lazy something, you are missing the chance to visit " + pageName);
          }
        }
    </script>

<footer>

</footer>
</body>
`

**Comment by wojski** [comment]
You hardcoded page name in function. (Hardcoded means some value is static in function, and there is no way to use this function for other purpose).
For egz. If you want to use this function for page3, you need to copy this function and change harcoded value page2 to page3.
In case like this is better to think about create a parametrize function where 1 parameter is "page name". Egz in 1st comment.

**Comment by rosaba** [comment]
ok, got it,thx! i wanna share my new code with you here, but somehow fail to paste it in as pure code. how can i do that ("insert code" does not work so far)?

**Comment by rosaba** [comment]
[index.txt](https://github.com/rosaba/test-repository/files/152418/index.txt)

**Comment by rosaba** [comment]
not very elegant to upload a file,sry.. how can I do it as you did above? that looks really good.

**Comment by wojski** [comment]
If you want to update you current code, you should clone you branch into work machine, "pull" newest version, then make changes in code and make commit.

Example tutorial how to do that:
(graphics version)
https://nathanj.github.io/gitguide/tour.html

(command line) - I propose to first learn how to use git with command line.
http://readwrite.com/2013/10/02/github-for-beginners-part-2

## **Best i think**
http://tutorial.djangogirls.org/en/deploy/index.html (GIT SECTION, step by step)

**Comment by rosaba** [comment]
i think it finally worked to commit and push the reworked index file, somehow at least, puh

**Comment by wojski** [comment]
Looks good.
Good shoot with Array to keep pages.

One suggestion.
If you use github to make exercise is good idea to think about create folder structure egz:

```
RootFolder (Base git folder)
     --- Exercises (Folder with exercises)
         ---Exercise1 (Folder with exercise)
```

And try to create branch for each exercise (Then you will be able to learn how to merge branches make rebases etc.)
